export const ActionTypes = {
        FETCH_QUESTIONS : 'FETCH_QUESTIONS',
        ADD_QUESTION : 'ADD_QUESTION',
        SUBMIT_QUESTIONS : 'SUBMIT_QUESTION',
        REMOVE_QUESTION : 'REMOVE_QUESTION',
        EDIT_QUESTION : 'EDIT_QUESTION',
        ADD_REVIEW : 'ADD_REVIEW',
        SUBMIT_BASIC_DETAILS : 'SUBMIT_BASIC_DETAILS',
        SET_BASIC_DETAILS : 'SET_BASIC_DETAILS',
        FETCH_BASIC_DETAILS : 'FETCH_BASIC_DETAILS',
        FETCH_BASIC_SUCESS : 'FETCH_BASIC_SUCESS',
        FETCH_BASIC_ERROR : 'FETCH_BASIC_ERROR',
}